authentication/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from authentication import views

app_name = 'authentication'

router = DefaultRouter()
router.register(r'accounts', views.AccountViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^auth/login/', views.account_login, name='login'),
    url(r'^auth/signup/', views.account_signup, name='signup'),
    url(r'^auth/logout/', views.account_logout, name='logout'), 
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

roombooking/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views 

app_name = "roombooking"

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^', include('rooms.urls')),
    url(r'^', include('bookings.urls')),
    url(r'^', include('authentication.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
]

rooms/urls.py
from django.conf.urls import url, include
from rooms import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'rooms', views.RoomViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls))
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


class AccountManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):
        if not email:
            raise ValueError('Users must have a valid email address.')

        if not kwargs.get('username'):
                    raise ValueError('Users must have a valid username.')

        account = self.model(
            email=self.normalize_email(email),
            username=kwargs.get('username'),
            name=kwargs.get('name', '')
        )

        account.set_password(password)
        account.save()

        return account

    def create_superuser(self, email, password, **kwargs):
        account = self.create_user(email, password, **kwargs)

        account.is_admin = True
        account.is_staff = True
        account.is_superuser = True
        account.is_verified = True
        account.is_active = True
        account.save()

        return account

class Account(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=40, unique=True)

    name = models.CharField(max_length=40, default="")
    is_admin = models.BooleanField(default=False)
    is_gsec = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = AccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __unicode__(self):
        return self.email

    def get_name(self):
        return self.name

authentication/forms.py
from django import forms

class AccountSignupForm(forms.Form):
    email = forms.CharField(required=True, label="Email", max_length=30)
    name = forms.CharField(required=True, label="Name", max_length=30)
    username = forms.CharField(required=True, label="Username", max_length=30)	
    password = forms.CharField(required=True, label='Password', max_length=30, widget=forms.PasswordInput())

class AccountLoginForm(forms.Form):
    email = forms.CharField(required=True, label="Email", max_length=30)
    password = forms.CharField(required=True, label='Password', max_length=30, widget=forms.PasswordInput())

authentication/views.py
from rest_framework import permissions, viewsets, status
from rest_framework.response import Response

from authentication.models import Account
from authentication.permissions import IsAccountOwner
from authentication.serializers import AccountSerializer

from authentication.forms import AccountLoginForm, AccountSignupForm
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django import forms
from django.contrib.auth import authenticate, login, logout
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text
from roombooking import settings

class AccountViewSet(viewsets.ModelViewSet):
    lookup_field = 'username'
    queryset = Account.objects.all()
    serializer_class = AccountSerializer

    def get_permissions(self):
        if self.request.method in permissions.SAFE_METHODS:
            return (permissions.AllowAny(),)

        if self.request.method == 'POST':
            return (permissions.AllowAny(),)

        return (permissions.IsAuthenticated(), IsAccountOwner(),)

    def create(self, request):
        serializer = self.serializer_class(data=request.data)
        
        if serializer.is_valid():
            Account.objects.create_user(**serializer.validated_data)

            return Response(serializer.validated_data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

def account_signup(request):
    if request.method == 'POST':
        form = AccountSignupForm(request.POST)
        if form.is_valid():
            account = form.cleaned_data

            username = account['username']
            email = account['email']
            name = account['name']
            password = account['password']

            args = {'username': username, 'name': name}
            if not (Account.objects.filter(username=username).exists() or Account.objects.filter(email=email).exists()):
                account = Account.objects.create_user(email, password, **args)
                account.is_active = False
                account.is_verified = False
                account.save()
                login(request, account)

                current_site = get_current_site(request)

                mail_subject = "Approve indepedent body's registration"
                message = render_to_string('authentication/activation_email.html', {
                    'user': 'GSec',
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(account.pk)).decode(),
                    'token': account_activation_token.make_token(account),
                    'account': account,
                })         
                
                to_email = "rohitrp@iitb.ac.in"
                email = EmailMessage(
                    mail_subject, message, to=[to_email]
                )
                print(email)
                email.send()

                return HttpResponseRedirect('/')

            else:
                raise forms.ValidationError('User already exists')

    else:
        form = AccountSignupForm()

    return render(request, 'authentication/signup.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        account = Account.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        account = None
    
    if account is not None and account_activation_token.check_token(account, token):
        account.is_active = True
        account.is_verified = True
        account.save()

        return HttpResponse('Account has been activated')
    else:
        return HttpResponse('Activtion link is invalid!')

def account_login(request):
    if request.method == "POST":
        form = AccountLoginForm(request.POST)
        if form.is_valid():
            account = form.cleaned_data
            email = account['email']
            password = account['password']

            account = authenticate(email=email, password=password)

            if account is not None:
                login(request, account)

                return HttpResponseRedirect('/')

            return HttpResponseRedirect('/auth/login/')
        
    else:
        form = AccountLoginForm()

    return render(request, 'authentication/login.html', {'form': form})

def account_logout(request):
    logout(request)

    return HttpResponseRedirect('/')

authentication/templates/authentication/activation_email.html
{% autoescape off %}
Hi {{ user }},

Following independent body's registration requires approval:

Name: {{ account.name }}
Email: {{ account.email }}

Please click on the link to approve it, 
http://{{ domain }}{% url 'authentication:activate' uidb64=uid token=token %}
{% endautoescape %}

authentication/templates/authentication/login.html
{% extends 'roombooking/base.html' %} 

{% block content %}
    <div class="row">
        <div class="col s6">
            <form method="POST">
                {% csrf_token %} {{ form.as_p }}
                
                <button class="btn waves-effect waves-light" type="submit" name="action">Login
                    <i class="material-icons right">send</i>
                </button>
            </form>
            {% if not login.empty %}
                <p>{{ login.message }}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/signup.html
{% extends 'roombooking/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-4 offset-md-2">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_email">Email:</label> 
                <input type="email" class="form-control" name="email" required id="id_email" maxlength="30" />
            </div>
            <div class="form-group">
                <label for="id_name">Name:</label> 
                <input type="name" class="form-control" name="name" required id="id_name" maxlength="30" />
            </div>
            <div class="form-group">
                <label for="id_username">Username:</label> 
                <input type="text" class="form-control" name="username" required id="id_username" maxlength="30" />
            </div>
            <div class="form-group">
                <label for="id_password">Password:</label> 
                <input type="password" class="form-control" name="password" required id="id_password" maxlength="30" />
            </div>
    
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" name="action">
                Signup
            </button>
        </form>
    </div>
</div>
{% endblock %}