authentication/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from authentication import views

app_name = 'authentication'

router = DefaultRouter()
router.register(r'accounts', views.AccountViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^auth/login/', views.account_login, name='login'),
    url(r'^auth/signup/', views.account_signup, name='signup'),
    url(r'^auth/logout/', views.account_logout, name='logout'), 
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

bookings/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from bookings import views

app_name = "bookings"

router = DefaultRouter()
router.register(r'bookings', views.BookingViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^bookings/create/$', views.create_booking, name='create-booking'),
    url(r'^bookings/$', views.show_bookings, name='show-bookings'),       
    url(r'^bookings/delete/(?P<pk>[0-9]+)/', views.delete_booking, name='delete-booking'),
    url(r'^bookings/approve/(?P<pk>[0-9]+)/', views.approve_booking, name='approve-booking'),
    url(r'^bookings/reject/(?P<pk>[0-9]+)/', views.reject_booking, name='reject-booking'),
    url(r'^bookings/conflict/$', views.booking_conflict, name='booking-conflict'),
]

roombooking/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views 

app_name = "roombooking"

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^', include('rooms.urls')),
    url(r'^', include('bookings.urls')),
    url(r'^', include('authentication.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
]

rooms/urls.py
from django.conf.urls import url, include
from rooms import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'rooms', views.RoomViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls))
]

bookings/models.py
from django.db import models
from rooms.models import Room

class Booking(models.Model):
    start = models.DateTimeField()
    end = models.DateTimeField()
    room_id = models.ForeignKey('rooms.Room', related_name='bookings', on_delete=models.CASCADE)
    account = models.ForeignKey('authentication.Account', related_name='bookings', on_delete=models.CASCADE)
    status = models.IntegerField(default=0) # 0 - Pending approval, 1 - Approved, 2 - Rejected
    # approved = models.BooleanField(default=False)
    # rejected = models.BooleanField(default=False)
    googleCalendarEventId = models.CharField(max_length=50, blank=True)

    class Meta:
        ordering = ['start']

    # def save(self, *args, **kwargs):
    #     super(Booking, self).save(*args, **kwargs)

    def __str__(self):
        return ' '.join([str(self.room_id), str(self.start), str(self.end)])

authentication/forms.py
from django import forms

class AccountSignupForm(forms.Form):
    email = forms.CharField(required=True, label="Email", max_length=30)
    name = forms.CharField(required=True, label="Name", max_length=30)
    username = forms.CharField(required=True, label="Username", max_length=30)	
    password = forms.CharField(required=True, label='Password', max_length=30, widget=forms.PasswordInput())

class AccountLoginForm(forms.Form):
    email = forms.CharField(required=True, label="Email", max_length=30)
    password = forms.CharField(required=True, label='Password', max_length=30, widget=forms.PasswordInput())

roombooking/views.py
from django.shortcuts import render
from django.db.models import Q
from bookings.models import Booking
from authentication.views import account_login

def home(request):
    if request.user.is_authenticated:
        if request.user.is_admin:
            bookings = Booking.objects.filter(~Q(status=1))
        else:
            bookings = Booking.objects.filter(~Q(status=1), account=request.user)
    else:        
        bookings = []
    return render(request, 'roombooking/home.html', {'total_bookings': len(bookings)})

roombooking/templates/roombooking/base.html
{% load staticfiles %}
<html>

<head>
    <title>SAC Room Booking</title>

    <link href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css' rel='stylesheet' />
    <link href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.print.css' rel='stylesheet' media='print' />


    <script src='http://momentjs.com/downloads/moment.js'></script>
    <script src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js'></script>

    <link href='https://use.fontawesome.com/releases/v5.0.6/css/all.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <style>
        
        #calendar {
            max-width: 900px;
            margin: 40px auto;
        }

        .font-awesome {
            font-size: 1.5em;
            margin: 0 10px;
        }

        .card {
            margin: 10px 0;
        }
    </style>
    <script>
            $(document).ready(function() {
                // $('select').formSelect();
                $('#calendar').fullCalendar({
                    themeSystem: 'bootstrap4',
                    header: {
                      left: 'prev,next today',
                      center: 'title',
                      right: 'month,agendaWeek,agendaDay,listMonth'
                    },
                    weekNumbers: true,
                    eventLimit: true, // allow "more" link when too many events
                    events: '/api/bookings/approved/'
                  });
                
                $('#id_room_id').addClass('form-control');
            });
        </script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">SAC Room Booking</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbar-menu">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authentication:signup' %}">Signup</a>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if not user.is_admin and user.is_verified  %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bookings:create-booking' %}">Create Booking</a>
                    </li>               
                {% endif %}    
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bookings:show-bookings' %}">
                        Bookings <span class="badge badge-secondary">{{ total_bookings }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authentication:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">Hello, {{ user.name }}</a>
                </li>
            {% endif %}
            </ul>
            {% if not user.is_authenticated %}
                <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'authentication:login' %}">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="email" name="email" required maxlength="30" id="id_email" placeholder="Email">
                    <input class="form-control mr-sm-2" type="password" name="password" required maxlength="30" id="id_password" placeholder="Password">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Login</button>
                </form>
            {% endif %}
        </div>
    </nav>

    {% if user.is_authenticated and not user.is_verified %}
        <div class="col alert alert-primary">
            Your account is pending verification.
        </div>
    {% endif %}


    {% block calendar %}
    {% endblock %}
      
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

roombooking/templates/roombooking/home.html
{% extends 'roombooking/base.html' %}

{% block calendar %}
    <div id="calendar"></div>

    <!-- <iframe src="https://calendar.google.com/calendar/embed?src=st49afvh9lm7us8qh06t1gokjg%40group.calendar.google.com&ctz=Asia%2FCalcutta" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe> -->
{% endblock %}