bookings/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from bookings import views

app_name = "bookings"

router = DefaultRouter()
router.register(r'bookings', views.BookingViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^bookings/create/$', views.create_booking, name='create-booking'),
    url(r'^bookings/$', views.show_bookings, name='show-bookings'),       
    url(r'^bookings/delete/(?P<pk>[0-9]+)/', views.delete_booking, name='delete-booking'),
    url(r'^bookings/approve/(?P<pk>[0-9]+)/', views.approve_booking, name='approve-booking'),
    url(r'^bookings/reject/(?P<pk>[0-9]+)/', views.reject_booking, name='reject-booking'),
    url(r'^bookings/conflict/$', views.booking_conflict, name='booking-conflict'),
]

roombooking/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views 

app_name = "roombooking"

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^', include('rooms.urls')),
    url(r'^', include('bookings.urls')),
    url(r'^', include('authentication.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
]

rooms/urls.py
from django.conf.urls import url, include
from rooms import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'rooms', views.RoomViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls))
]

bookings/models.py
from django.db import models
from rooms.models import Room

class Booking(models.Model):
    start = models.DateTimeField()
    end = models.DateTimeField()
    room_id = models.ForeignKey('rooms.Room', related_name='bookings', on_delete=models.CASCADE)
    account = models.ForeignKey('authentication.Account', related_name='bookings', on_delete=models.CASCADE)
    status = models.IntegerField(default=0) # 0 - Pending approval, 1 - Approved, 2 - Rejected
    # approved = models.BooleanField(default=False)
    # rejected = models.BooleanField(default=False)
    googleCalendarEventId = models.CharField(max_length=50, blank=True)

    class Meta:
        ordering = ['start']

    # def save(self, *args, **kwargs):
    #     super(Booking, self).save(*args, **kwargs)

    def __str__(self):
        return ' '.join([str(self.room_id), str(self.start), str(self.end)])

bookings/forms.py
from django import forms
from .models import Booking

class BookingForm(forms.ModelForm):
    start = forms.CharField()
    end = forms.CharField()

    class Meta:
        model = Booking
        fields = ('start', 'end', 'room_id')

bookings/views.py
import httplib2
import os
import datetime

from bookings.models import Booking
from bookings.serializers import BookingSerializer
from rooms.models import Room
from rest_framework import permissions
from bookings.permissions import IsOwnerOrReadOnly
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.decorators import list_route
from rest_framework import status
import dateutil.parser
import pytz

from django.shortcuts import render, HttpResponseRedirect
from .forms import BookingForm
from django.template.loader import render_to_string
from django.core.mail import EmailMessage

from apiclient import discovery
from oauth2client import client
from oauth2client import tools
from oauth2client.file import Storage
from decouple import config

# For google calendar
# try:
#     import argparse
#     flags = argparse.ArgumentParser(parents=[tools.argparser]).parse_args()
# except ImportError:
#     flags = None

SCOPES = 'https://www.googleapis.com/auth/calendar'
CLIENT_SECRET_FILE = 'client_secret.json'
APPLICATION_NAME = 'Google Calendar API (SAC Room Booking)'

utc=pytz.UTC

class BookingViewSet(viewsets.ModelViewSet):
    """
    List all bookings, create, retrieve, update
    and destroy a booking
    """
    queryset = Booking.objects.all()
    serializer_class = BookingSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,
                          IsOwnerOrReadOnly)

    def perform_create(self, serializer):
        serializer.save(account=self.request.user)

    # def get_parsed_date(self, date):
    #     return dateutil.parser.parse(date)

    def check_date_range_conflict(self, request, serializer):
        start = serializer.validated_data['start']
        end = serializer.validated_data['end']

        if start > end:
            return Response(status=status.HTTP_406_NOT_ACCEPTABLE)

        bookings = Booking.objects.filter(room_id=serializer.validated_data['room_id'])
        
        for booking in bookings:
            curr_start = booking.start
            curr_end = booking.end

            if (curr_start <= start and start <= curr_end):
                return Response(BookingSerializer(booking).data, status=status.HTTP_406_NOT_ACCEPTABLE)

            if (curr_start <= end and end <= curr_end):
                return Response(BookingSerializer(booking).data, status=status.HTTP_406_NOT_ACCEPTABLE)

        serializer.save(account=request.user)
        return Response(serializer.data)

    def create(self, request, pk=None, format=None):
        serializer = BookingSerializer(data=request.data)
        print(request.data)

        if serializer.is_valid():
            return self.check_date_range_conflict(request, serializer)

    @list_route(methods=['get'], url_path='approved')
    def approved(self, request):
        approved_bookings = Booking.objects.filter(status=1)
        serializer = BookingSerializer(approved_bookings, many=True)
        return Response(serializer.data)

    # TODO: Implement method to update booking dates

def get_conflicted_booking_or_false(booking):

    start = booking.start.replace(tzinfo=utc)
    end = booking.end.replace(tzinfo=utc)
    
    for _booking in Booking.objects.filter(room_id=booking.room_id, status=1):
        curr_start = _booking.start.replace(tzinfo=utc)
        curr_end = _booking.end.replace(tzinfo=utc)

        if booking.id == _booking.id:
            continue

        # check if bookings overlap
        if start <= curr_end and curr_start <= end:
            return _booking
    
    return False

def get_google_calendar_credentials():
    home_dir = os.path.expanduser('~')
    credential_dir = os.path.join(home_dir, '.credentials')
    if not os.path.exists(credential_dir):
        os.makedirs(credential_dir)

    credential_path = os.path.join(credential_dir,
                                   'sac-room-booking-calendar.json')

    store = Storage(credential_path)
    credentials = store.get()

    if not credentials or credentials.invalid:
        flow = client.flow_from_clientsecrets(CLIENT_SECRET_FILE, SCOPES)
        flow.user_agent = APPLICATION_NAME
        flags = tools.argparser.parse_args(args=[])
        credentials = tools.run_flow(flow, store, flags)
        print('Storing credentials to ' + credential_path)

    return credentials

def get_google_calendar_service():
    credentials = get_google_calendar_credentials()
    http = credentials.authorize(httplib2.Http())
    service = discovery.build('calendar', 'v3', http=http)

    return service

def create_calendar_event(booking):
    service = get_google_calendar_service()

    event = {
        'summary': booking.account.name,
        'location': str(booking.room_id),
        'description': '',
        'start': {
            'dateTime': booking.start.isoformat(),
            'timeZone': 'Asia/Kolkata',
        },
        'end': {
            'dateTime': booking.end.isoformat(),
            'timeZone': 'Asia/Kolkata',
        },
        'attendees': [
            {'email': booking.account.email},
        ],
        'reminders': {
            'useDefault': False,
            'overrides': [
            {'method': 'email', 'minutes': 24 * 60},
            {'method': 'popup', 'minutes': 10},
            ],
        }
    }

    event = service.events().insert(
        calendarId=config('CALENDAR_ID'),
        body=event).execute()

    booking.googleCalendarEventId = event['id']
    return event

def delete_google_calendar_event(booking):
    service = get_google_calendar_service()

    service.events().delete(
        calendarId=config('CALENDAR_ID'),
        eventId=booking.googleCalendarEventId
    ).execute()

def create_booking(request):
    if request.method == 'POST':
        form = BookingForm(data=request.POST)
        if form.is_valid():
            booking = form.save(commit=False)

            # TODO: Check if booking date/time is not before current date/time

            if booking.start > booking.end:
                return render(request, 'bookings/create_booking.html', {'form': form, 'msg': 'Invalid date range'})

            # _booking will be Booking object if there is a conflict
            # or False otherwise
            _booking = get_conflicted_booking_or_false(booking)

            if _booking != False:
                return render(request, 'bookings/create_booking.html', {'form': form, 'booking': [_booking], 'msg': 'Conflicts with following booking:'})
            
            booking.account=request.user
            booking.save()
            
            return HttpResponseRedirect('/bookings')
        else:
            return render(render(request, 'bookings/create_booking.html', {'form': form, 'msg': 'Form not valid!'}))        
    else:
        form = BookingForm()

    return render(request, 'bookings/create_booking.html', {'form': form})

def show_bookings(request):
    if request.user.is_admin:
        bookings = Booking.objects.filter()
    else:
        bookings = Booking.objects.filter(account=request.user)
    return render(request, 'bookings/show_bookings.html', {'bookings': bookings})

def send_email(request, status, booking):
    if not request.user.is_admin:
        return
    subject = "SAC Room Booking status"

    message = render_to_string('bookings/booking_email.html', {
        'account': booking.account,
        'booking': booking,
        'status': status
    })

    to_email = booking.account.email
    email = EmailMessage(
        subject, message, to=[to_email]
    )

    email.send()

def delete_booking(request, pk):
    booking = Booking.objects.get(id=pk)
    send_email(request, "deleted", booking)
    # delete_google_calendar_event(booking)
    booking.delete()
    return HttpResponseRedirect('/bookings/')

def approve_booking(request, pk):
    booking = Booking.objects.get(id=pk)

    _booking = get_conflicted_booking_or_false(booking)

    if _booking != False:
        return HttpResponseRedirect('/bookings/conflict?id1=' + str(booking.id) + '&id2=' + str(_booking.id))

    booking.status = 1
    # create_calendar_event(booking)
    booking.save()
    send_email(request, "approved", booking)  
 
    return HttpResponseRedirect('/bookings/')

def booking_conflict(request):
    booking1 = Booking.objects.get(id=request.GET.get('id1'))
    booking2 = Booking.objects.get(id=request.GET.get('id2'))

    return render(request, 'bookings/booking_conflict.html', {'bookings': [booking1, booking2]})

def reject_booking(request, pk):
    booking = Booking.objects.get(id=pk)
    booking.status = 2
    # delete_google_calendar_event(booking)
    booking.save()
    send_email(request, "rejected", booking)    
    return HttpResponseRedirect('/bookings/')

bookings/templates/bookings/booking.html
{% comment %} <h1 class="display-6">{{ title }}</h1> {% endcomment %}

{% for booking in bookings %}
    <div class="card border-secondary">
    <div class="card-header">
        {{ booking.account.name }}
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ booking.room_id }}</h5>
        <p class="card-text">
            <b>From:</b> {{ booking.start|date:"M d, Y g:m A" }} <br>
            <b>To:</b> {{ booking.end|date:"M d, Y g:m A"}} <br>
            <b>Room:</b> {{ booking.room_id }} <br>
            <b>Status:</b>
            {% if booking.status == 0 %} Pending Approval 
            {% elif booking.status == 1 %} Approved 
            {% else %} Rejected 
            {% endif %}
        </p>
    </div>
    <div class="card-footer text-muted">
        {% if user.is_admin %}
            <a href="/bookings/approve/{{booking.id}}" style="color: rgb(117, 117, 117);">
                <i class="fas fa-check font-awesome"></i>
            </a>
            <a href="/bookings/reject/{{booking.id}}" style="color: rgb(117, 117, 117);">
                <i class="fas fa-times font-awesome"></i>
            </a>
        {% endif %}
        {% if user == booking.account or user.is_admin %}
            <a href="/bookings/delete/{{booking.id}}" style="color: rgb(117, 117, 117);">
                <i class="fas fa-trash font-awesome"></i>
            </a>
        {% endif %}
    </div>
    </div>
{% endfor %}

bookings/templates/bookings/booking_conflict.html
{% extends 'roombooking/base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12">
            {% include 'bookings/booking.html' with bookings=bookings title="Following bookings conflicts with each other:" %}
        </div>
    </div>
{% endblock %}

bookings/templates/bookings/booking_email.html
{% autoescape off %}
Hi {{ account.name }},

Your booking:
Room: {{ booking.room_id }}
From: {{ booking.start }}
To: {{ booking.end }}

has been {{ status }} by the admin.

{% endautoescape %}

bookings/templates/bookings/create_booking.html
{% extends 'roombooking/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-4 offset-md-2">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_start">Booking from:</label> 
                    <input type="datetime-local" class="form-control" name="start" required id="id_start" />
                </div>
                <div class="form-group">
                    <label for="id_end">Booking to:</label> 
                    <input type="datetime-local" class="form-control" name="end" required id="id_end" />
                </div>
                <div class="form-group">
                    <label for="id_room_id">Room</label>
                    {{ form.room_id }}
                </div>
                
                <button class="btn btn-outline-dark" type="submit" name="action">Submit</button>

                </form>
            <p>{{ msg }}</p>
        </div>
    </div>

    {% if booking %}
        {% include 'bookings/booking.html' with bookings=booking title=msg %}
    {% endif %}
{% endblock %}

bookings/templates/bookings/show_bookings.html
{% extends 'roombooking/base.html' %}

{% block content %}

    <div class="row">
        <div class="col-md-6 offset-md-1">
            {% include 'bookings/booking.html' with bookings=bookings title="Bookings" %}
        </div>
    </div>

{% endblock %}